参照：  
Numpy：http://tanukigraph.hatenablog.com/entry/2017/08/23/195756  
Pandas：http://sinhrks.hatenablog.com/entry/2015/01/28/073327

Numpyにおけるndarrayの連結方法は以下：
1. `concatenate`
2. `stack`
3. `vstack` & `hstack`
4. `append`

PandasにおけるSeries, DataFrameの連結方法は以下：
1. `pd.concat`：DataFrame.concatではない
2. `pd.merge`
3. `DataFrame.join`

## Numpyにおけるndarrayの連結方法

In [13]:
# サンプルコード用
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[1,2],[3,4],[5,6]])

### concatenate

引数axisは連結の方向を指定します。0だと行が増え、1だと列が増える方向です。  
また、concatenateは連結によって次元を上げることは出来ません。

大きさの異なる配列同士の連結も、連結断面の要素数が同じならば可能です。例えば、配列aとcは列の数は同じですが、行の数が異なります。この時、axis=0でconcatenateは可能ですが、axis=1ではエラーとなり実行できません。

In [2]:
np.concatenate([a,b],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
np.concatenate([a,b],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### stack
stackは次元を上げます。2つの配列を重ねるイメージです。  
stackは異なる大きさの配列を連結することはできません。

In [5]:
np.stack([a,b],axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
np.stack([a,b],axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

### vstack, hstack
vstackとhstackですが、名前に惑わされてはいけません。できることはconcatenateと同様です。
vstackとhstackは引数にaxisを取りません。vstackはconcatenateでaxisを0に指定したもの、hstackはaxisを1に指定したものと同じです。

大きさの異なる配列同士の連結も、連結断面の要素数が同じならば可能です。

In [9]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [8]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
np.vstack([a,c])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [5, 6]])

### append
元の配列に別の配列を付け加えます。appendはaxisを指定できますが、何も指定しないと元が多次元配列でも1次元にされてしまいます。

In [11]:
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.append(a,b, axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## PandasにおけるSeries, DataFrameの連結方法

In [14]:
# サンプルコード用
import pandas as pd

left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K1', 'K3', 'K5', 'K7'],
                      'C': ['C1', 'C3', 'C5', 'C7'],
                      'D': ['D1', 'D3', 'D5', 'D7']},
                     index=[1, 3, 5, 7])